---
services:
  freqtrade:
    container_name: qa_dryrun_top30_dualrun
    command:
      - trade
      - --config
      - user_data/config.json
      - --config
      - /freqtrade/configs/pairlist-static-bybit-futures-usdt-top30.json
      - --config
      - user_data/config.windows-gpu.json
      - --config
      - user_data/config.dryrun-wsl-top30-dualrun.json
      - --strategy-path
      - user_data/strategies
      - --strategy
      - QuickAdapterV3
