---
services:
  freqtrade:
    container_name: reforcexy_dryrun_top30_dualrun
    command:
      - trade
      - --config
      - user_data/config.json
      - --config
      - /freqtrade/configs/pairlist-static-bybit-futures-usdt-top30.json
      - --strategy-path
      - user_data/strategies
      - --strategy
      - RLAgentStrategy
